version: '2'
services:
  db:
    image: greyarch/rethinkdb
    ports:
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
  web:
    image: mhart/alpine-node-auto
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "33000:3000"
    depends_on:
      - db
