mysql:
  image: mysql
  ports:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: 12345
    MYSQL_DATABASE: db_test
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
    - PMA_ARBITRARY=1
  restart: always
  ports:
    - "8080:80"
  volumes:
    - /session
